-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO public.order_status (id, label) VALUES
-- ('NEW', 'New'),
-- ('IN_PROGRESS', 'In Progress'),
-- ('DONE', 'Done'),
-- ('CANCELED', 'Canceled'),
-- ('DELIVERED', 'Delivered');
